# Generated by Django 4.0.3 on 2022-04-03 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='act',
            name='images',
            field=models.CharField(default=1, max_length=250),
            preserve_default=False,
        ),
    ]
