# Generated by Django 4.0.3 on 2022-04-06 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_act_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=250)),
                ('weather', models.CharField(max_length=100)),
                ('active', models.CharField(choices=[(1, 'Couch Potato'), (2, 'Not As Active'), (3, 'Active'), (4, 'Sort of Active'), (5, 'Triathlon')], max_length=40)),
            ],
        ),
    ]
