# Generated by Django 4.0.3 on 2022-04-06 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='act',
            name='label',
            field=models.CharField(choices=[('Food', 'food'), ('Activity', 'activity')], max_length=20),
        ),
    ]
