# Generated by Django 4.0.3 on 2022-04-07 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_alter_review_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='act',
            name='review',
            field=models.ManyToManyField(to='main_app.review'),
        ),
    ]
